services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - /home/asfor_a/Apps/mongo-data:/data/db
    networks:
      - dev_net
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  dev_net:
    driver: bridge

